# Generated by Django 4.2.1 on 2023-06-26 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skilllist',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
