# Generated by Django 4.2.1 on 2023-05-16 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='list_description',
            field=models.ManyToManyField(to='about.skilllist'),
        ),
    ]
