# Generated by Django 4.2.1 on 2023-05-15 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_aboutfaq_aboutfaqlist_aboutskill_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AboutSkill',
            new_name='Skill',
        ),
        migrations.RenameModel(
            old_name='AboutSkillList',
            new_name='SkillList',
        ),
        migrations.RenameModel(
            old_name='AboutFaqList',
            new_name='Why',
        ),
        migrations.RenameModel(
            old_name='AboutFAQ',
            new_name='WhyList',
        ),
    ]
