# Generated by Django 4.2.1 on 2023-06-26 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_alter_skilllist_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutlist',
            name='item',
            field=models.TextField(),
        ),
    ]
