# Generated by Django 4.2.1 on 2023-05-15 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_rename_aboutskill_skill_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='list_description',
        ),
        migrations.AddField(
            model_name='about',
            name='list_description',
            field=models.ManyToManyField(to='about.aboutlist'),
        ),
    ]
