# Generated by Django 4.2.1 on 2023-05-15 21:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricinglist',
            name='descriptionlist',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='pricing.pricingdescriptionlist'),
            preserve_default=False,
        ),
    ]
